/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExamCategory = { 'rms' : null } |
  { 'sainikSchool' : null } |
  { 'rimc' : null } |
  { 'navodaya' : null };
export interface LeaderboardEntry {
  'principal' : Principal,
  'total' : bigint,
  'scorePercentage' : bigint,
  'timestamp' : bigint,
  'testTitle' : string,
}
export interface MockTest {
  'id' : bigint,
  'title' : string,
  'examCategory' : ExamCategory,
  'durationMinutes' : bigint,
  'questionIds' : Array<bigint>,
}
export interface PracticeQuestion {
  'id' : bigint,
  'topic' : string,
  'question' : string,
  'subject' : Subject,
  'explanation' : string,
  'correctAnswer' : bigint,
  'examCategory' : ExamCategory,
  'options' : Array<string>,
}
export interface Question {
  'id' : bigint,
  'topic' : string,
  'question' : string,
  'subject' : Subject,
  'explanation' : string,
  'correctAnswer' : bigint,
  'examCategory' : ExamCategory,
  'options' : Array<string>,
}
export interface QuestionInput {
  'topic' : string,
  'question' : string,
  'subject' : Subject,
  'explanation' : string,
  'correctAnswer' : bigint,
  'examCategory' : ExamCategory,
  'options' : Array<string>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StudyNote {
  'id' : bigint,
  'topic' : string,
  'content' : string,
  'subject' : Subject,
  'examCategory' : ExamCategory,
}
export interface StudyNoteInput {
  'topic' : string,
  'content' : string,
  'subject' : Subject,
  'examCategory' : ExamCategory,
}
export type Subject = { 'gk' : null } |
  { 'math' : null } |
  { 'reasoning' : null } |
  { 'english' : null };
export interface TestAttempt {
  'principal' : Principal,
  'total' : bigint,
  'answers' : Array<bigint>,
  'score' : bigint,
  'timestamp' : bigint,
  'timeTaken' : bigint,
  'testId' : bigint,
}
export interface TestSubmissionResult {
  'total' : bigint,
  'score' : bigint,
  'timeTaken' : bigint,
  'percentage' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'examCategory' : [] | [ExamCategory],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<[QuestionInput], undefined>,
  'addStudyNote' : ActorMethod<[StudyNoteInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], undefined>,
  'clearRazorpayKeyId' : ActorMethod<[], undefined>,
  'clearStripeConfiguration' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createMockTest' : ActorMethod<
    [string, ExamCategory, Array<bigint>, bigint],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboardByCategory' : ActorMethod<
    [ExamCategory],
    Array<LeaderboardEntry>
  >,
  'getMockTestById' : ActorMethod<
    [bigint],
    { 'test' : MockTest, 'questions' : Array<Question> }
  >,
  'getMockTestsByCategory' : ActorMethod<[ExamCategory], Array<MockTest>>,
  'getNotesByCategoryAndSubject' : ActorMethod<
    [ExamCategory, Subject],
    Array<StudyNote>
  >,
  'getPracticeQuestions' : ActorMethod<
    [ExamCategory, Subject],
    Array<PracticeQuestion>
  >,
  'getQuestionsByCategoryAndSubject' : ActorMethod<
    [ExamCategory, Subject],
    Array<Question>
  >,
  'getRazorpayKeyId' : ActorMethod<[], [] | [string]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserAttempts' : ActorMethod<[], Array<TestAttempt>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRazorpayConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRazorpayKeyId' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitTestAttempt' : ActorMethod<
    [bigint, Array<bigint>, bigint],
    TestSubmissionResult
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];