/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExamCategory = IDL.Variant({
  'rms' : IDL.Null,
  'sainikSchool' : IDL.Null,
  'rimc' : IDL.Null,
  'navodaya' : IDL.Null,
});
export const Subject = IDL.Variant({
  'gk' : IDL.Null,
  'math' : IDL.Null,
  'reasoning' : IDL.Null,
  'english' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'examCategory' : IDL.Opt(ExamCategory),
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'total' : IDL.Nat,
  'scorePercentage' : IDL.Nat,
  'timestamp' : IDL.Int,
  'testTitle' : IDL.Text,
});
export const MockTest = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'examCategory' : ExamCategory,
  'durationMinutes' : IDL.Nat,
  'questionIds' : IDL.Vec(IDL.Nat),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'subject' : Subject,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'examCategory' : ExamCategory,
  'options' : IDL.Vec(IDL.Text),
});
export const StudyNote = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'subject' : Subject,
  'examCategory' : ExamCategory,
});
export const TestAttempt = IDL.Record({
  'principal' : IDL.Principal,
  'total' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'timeTaken' : IDL.Nat,
  'testId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func(
      [
        ExamCategory,
        Subject,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addStudyNote' : IDL.Func(
      [ExamCategory, Subject, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMockTest' : IDL.Func(
      [IDL.Text, ExamCategory, IDL.Vec(IDL.Nat), IDL.Nat],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboardByCategory' : IDL.Func(
      [ExamCategory],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMockTestById' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'test' : MockTest, 'questions' : IDL.Vec(Question) })],
      ['query'],
    ),
  'getMockTestsByCategory' : IDL.Func(
      [ExamCategory],
      [IDL.Vec(MockTest)],
      ['query'],
    ),
  'getNotesByCategoryAndSubject' : IDL.Func(
      [ExamCategory, Subject],
      [IDL.Vec(StudyNote)],
      ['query'],
    ),
  'getPracticeQuestions' : IDL.Func(
      [ExamCategory, Subject],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByCategoryAndSubject' : IDL.Func(
      [ExamCategory, Subject],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getUserAttempts' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitTestAttempt' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'score' : IDL.Nat })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExamCategory = IDL.Variant({
    'rms' : IDL.Null,
    'sainikSchool' : IDL.Null,
    'rimc' : IDL.Null,
    'navodaya' : IDL.Null,
  });
  const Subject = IDL.Variant({
    'gk' : IDL.Null,
    'math' : IDL.Null,
    'reasoning' : IDL.Null,
    'english' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'examCategory' : IDL.Opt(ExamCategory),
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'total' : IDL.Nat,
    'scorePercentage' : IDL.Nat,
    'timestamp' : IDL.Int,
    'testTitle' : IDL.Text,
  });
  const MockTest = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'examCategory' : ExamCategory,
    'durationMinutes' : IDL.Nat,
    'questionIds' : IDL.Vec(IDL.Nat),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'subject' : Subject,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'examCategory' : ExamCategory,
    'options' : IDL.Vec(IDL.Text),
  });
  const StudyNote = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'subject' : Subject,
    'examCategory' : ExamCategory,
  });
  const TestAttempt = IDL.Record({
    'principal' : IDL.Principal,
    'total' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'timeTaken' : IDL.Nat,
    'testId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func(
        [
          ExamCategory,
          Subject,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addStudyNote' : IDL.Func(
        [ExamCategory, Subject, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMockTest' : IDL.Func(
        [IDL.Text, ExamCategory, IDL.Vec(IDL.Nat), IDL.Nat],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboardByCategory' : IDL.Func(
        [ExamCategory],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMockTestById' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'test' : MockTest, 'questions' : IDL.Vec(Question) })],
        ['query'],
      ),
    'getMockTestsByCategory' : IDL.Func(
        [ExamCategory],
        [IDL.Vec(MockTest)],
        ['query'],
      ),
    'getNotesByCategoryAndSubject' : IDL.Func(
        [ExamCategory, Subject],
        [IDL.Vec(StudyNote)],
        ['query'],
      ),
    'getPracticeQuestions' : IDL.Func(
        [ExamCategory, Subject],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByCategoryAndSubject' : IDL.Func(
        [ExamCategory, Subject],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getUserAttempts' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitTestAttempt' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'score' : IDL.Nat })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };