/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Variant({
  'gk' : IDL.Null,
  'math' : IDL.Null,
  'reasoning' : IDL.Null,
  'english' : IDL.Null,
});
export const ExamCategory = IDL.Variant({
  'rms' : IDL.Null,
  'sainikSchool' : IDL.Null,
  'rimc' : IDL.Null,
  'navodaya' : IDL.Null,
});
export const QuestionInput = IDL.Record({
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'subject' : Subject,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'examCategory' : ExamCategory,
  'options' : IDL.Vec(IDL.Text),
});
export const StudyNoteInput = IDL.Record({
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'subject' : Subject,
  'examCategory' : ExamCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'examCategory' : IDL.Opt(ExamCategory),
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'total' : IDL.Nat,
  'scorePercentage' : IDL.Nat,
  'timestamp' : IDL.Int,
  'testTitle' : IDL.Text,
});
export const MockTest = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'examCategory' : ExamCategory,
  'durationMinutes' : IDL.Nat,
  'questionIds' : IDL.Vec(IDL.Nat),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'subject' : Subject,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'examCategory' : ExamCategory,
  'options' : IDL.Vec(IDL.Text),
});
export const StudyNote = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'subject' : Subject,
  'examCategory' : ExamCategory,
});
export const PracticeQuestion = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'subject' : Subject,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'examCategory' : ExamCategory,
  'options' : IDL.Vec(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TestAttempt = IDL.Record({
  'principal' : IDL.Principal,
  'total' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'timeTaken' : IDL.Nat,
  'testId' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const TestSubmissionResult = IDL.Record({
  'total' : IDL.Nat,
  'score' : IDL.Nat,
  'timeTaken' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func([QuestionInput], [], []),
  'addStudyNote' : IDL.Func([StudyNoteInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [], []),
  'clearRazorpayKeyId' : IDL.Func([], [], []),
  'clearStripeConfiguration' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createMockTest' : IDL.Func(
      [IDL.Text, ExamCategory, IDL.Vec(IDL.Nat), IDL.Nat],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboardByCategory' : IDL.Func(
      [ExamCategory],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMockTestById' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'test' : MockTest, 'questions' : IDL.Vec(Question) })],
      ['query'],
    ),
  'getMockTestsByCategory' : IDL.Func(
      [ExamCategory],
      [IDL.Vec(MockTest)],
      ['query'],
    ),
  'getNotesByCategoryAndSubject' : IDL.Func(
      [ExamCategory, Subject],
      [IDL.Vec(StudyNote)],
      ['query'],
    ),
  'getPracticeQuestions' : IDL.Func(
      [ExamCategory, Subject],
      [IDL.Vec(PracticeQuestion)],
      ['query'],
    ),
  'getQuestionsByCategoryAndSubject' : IDL.Func(
      [ExamCategory, Subject],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserAttempts' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRazorpayKeyId' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitTestAttempt' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
      [TestSubmissionResult],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Variant({
    'gk' : IDL.Null,
    'math' : IDL.Null,
    'reasoning' : IDL.Null,
    'english' : IDL.Null,
  });
  const ExamCategory = IDL.Variant({
    'rms' : IDL.Null,
    'sainikSchool' : IDL.Null,
    'rimc' : IDL.Null,
    'navodaya' : IDL.Null,
  });
  const QuestionInput = IDL.Record({
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'subject' : Subject,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'examCategory' : ExamCategory,
    'options' : IDL.Vec(IDL.Text),
  });
  const StudyNoteInput = IDL.Record({
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'subject' : Subject,
    'examCategory' : ExamCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'examCategory' : IDL.Opt(ExamCategory),
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'total' : IDL.Nat,
    'scorePercentage' : IDL.Nat,
    'timestamp' : IDL.Int,
    'testTitle' : IDL.Text,
  });
  const MockTest = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'examCategory' : ExamCategory,
    'durationMinutes' : IDL.Nat,
    'questionIds' : IDL.Vec(IDL.Nat),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'subject' : Subject,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'examCategory' : ExamCategory,
    'options' : IDL.Vec(IDL.Text),
  });
  const StudyNote = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'subject' : Subject,
    'examCategory' : ExamCategory,
  });
  const PracticeQuestion = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'subject' : Subject,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'examCategory' : ExamCategory,
    'options' : IDL.Vec(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TestAttempt = IDL.Record({
    'principal' : IDL.Principal,
    'total' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'timeTaken' : IDL.Nat,
    'testId' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const TestSubmissionResult = IDL.Record({
    'total' : IDL.Nat,
    'score' : IDL.Nat,
    'timeTaken' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func([QuestionInput], [], []),
    'addStudyNote' : IDL.Func([StudyNoteInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [], []),
    'clearRazorpayKeyId' : IDL.Func([], [], []),
    'clearStripeConfiguration' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createMockTest' : IDL.Func(
        [IDL.Text, ExamCategory, IDL.Vec(IDL.Nat), IDL.Nat],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboardByCategory' : IDL.Func(
        [ExamCategory],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMockTestById' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'test' : MockTest, 'questions' : IDL.Vec(Question) })],
        ['query'],
      ),
    'getMockTestsByCategory' : IDL.Func(
        [ExamCategory],
        [IDL.Vec(MockTest)],
        ['query'],
      ),
    'getNotesByCategoryAndSubject' : IDL.Func(
        [ExamCategory, Subject],
        [IDL.Vec(StudyNote)],
        ['query'],
      ),
    'getPracticeQuestions' : IDL.Func(
        [ExamCategory, Subject],
        [IDL.Vec(PracticeQuestion)],
        ['query'],
      ),
    'getQuestionsByCategoryAndSubject' : IDL.Func(
        [ExamCategory, Subject],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserAttempts' : IDL.Func([], [IDL.Vec(TestAttempt)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRazorpayKeyId' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitTestAttempt' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat],
        [TestSubmissionResult],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };