/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PracticeQuestion {
    id: bigint;
    topic: string;
    question: string;
    subject: Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: ExamCategory;
    options: Array<string>;
}
export interface MockTest {
    id: bigint;
    title: string;
    examCategory: ExamCategory;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
}
export interface LeaderboardEntry {
    principal: Principal;
    total: bigint;
    scorePercentage: bigint;
    timestamp: bigint;
    testTitle: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface StudyNoteInput {
    topic: string;
    content: string;
    subject: Subject;
    examCategory: ExamCategory;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TestSubmissionResult {
    total: bigint;
    score: bigint;
    timeTaken: bigint;
    percentage: bigint;
}
export interface TestAttempt {
    principal: Principal;
    total: bigint;
    answers: Array<bigint>;
    score: bigint;
    timestamp: bigint;
    timeTaken: bigint;
    testId: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface QuestionInput {
    topic: string;
    question: string;
    subject: Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: ExamCategory;
    options: Array<string>;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface StudyNote {
    id: bigint;
    topic: string;
    content: string;
    subject: Subject;
    examCategory: ExamCategory;
}
export interface UserProfile {
    name: string;
    examCategory?: ExamCategory;
}
export interface Question {
    id: bigint;
    topic: string;
    question: string;
    subject: Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: ExamCategory;
    options: Array<string>;
}
export enum ExamCategory {
    rms = "rms",
    sainikSchool = "sainikSchool",
    rimc = "rimc",
    navodaya = "navodaya"
}
export enum Subject {
    gk = "gk",
    math = "math",
    reasoning = "reasoning",
    english = "english"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addQuestion(questionInput: QuestionInput): Promise<void>;
    addStudyNote(noteInput: StudyNoteInput): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimFirstAdmin(): Promise<void>;
    claimAdminWithCode(code: string): Promise<boolean>;
    clearRazorpayKeyId(): Promise<void>;
    clearStripeConfiguration(): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createMockTest(title: string, examCategory: ExamCategory, questionIds: Array<bigint>, durationMinutes: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboardByCategory(cat: ExamCategory): Promise<Array<LeaderboardEntry>>;
    getMockTestById(id: bigint): Promise<{
        test: MockTest;
        questions: Array<Question>;
    }>;
    getMockTestsByCategory(cat: ExamCategory): Promise<Array<MockTest>>;
    getNotesByCategoryAndSubject(cat: ExamCategory, subj: Subject): Promise<Array<StudyNote>>;
    getPracticeQuestions(cat: ExamCategory, subj: Subject): Promise<Array<PracticeQuestion>>;
    getQuestionsByCategoryAndSubject(cat: ExamCategory, subj: Subject): Promise<Array<Question>>;
    getRazorpayKeyId(): Promise<string | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserAttempts(): Promise<Array<TestAttempt>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isRazorpayConfigured(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setRazorpayKeyId(key: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitTestAttempt(testId: bigint, answers: Array<bigint>, timeTaken: bigint): Promise<TestSubmissionResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { ExamCategory as _ExamCategory, MockTest as _MockTest, PracticeQuestion as _PracticeQuestion, Question as _Question, QuestionInput as _QuestionInput, StripeSessionStatus as _StripeSessionStatus, StudyNote as _StudyNote, StudyNoteInput as _StudyNoteInput, Subject as _Subject, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addQuestion(arg0: QuestionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(to_candid_QuestionInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(to_candid_QuestionInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStudyNote(arg0: StudyNoteInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudyNote(to_candid_StudyNoteInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudyNote(to_candid_StudyNoteInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimFirstAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimFirstAdmin();
            return result;
        }
    }

    async claimAdminWithCode(code: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdminWithCode(code);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdminWithCode(code);
            return result;
        }
    }
    async clearRazorpayKeyId(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearRazorpayKeyId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearRazorpayKeyId();
            return result;
        }
    }
    async clearStripeConfiguration(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearStripeConfiguration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearStripeConfiguration();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createMockTest(arg0: string, arg1: ExamCategory, arg2: Array<bigint>, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMockTest(arg0, to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMockTest(arg0, to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboardByCategory(arg0: ExamCategory): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboardByCategory(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboardByCategory(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMockTestById(arg0: bigint): Promise<{
        test: MockTest;
        questions: Array<Question>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTestById(arg0);
                return from_candid_record_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTestById(arg0);
            return from_candid_record_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockTestsByCategory(arg0: ExamCategory): Promise<Array<MockTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTestsByCategory(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTestsByCategory(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByCategoryAndSubject(arg0: ExamCategory, arg1: Subject): Promise<Array<StudyNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByCategoryAndSubject(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByCategoryAndSubject(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPracticeQuestions(arg0: ExamCategory, arg1: Subject): Promise<Array<PracticeQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPracticeQuestions(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPracticeQuestions(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByCategoryAndSubject(arg0: ExamCategory, arg1: Subject): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByCategoryAndSubject(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByCategoryAndSubject(to_candid_ExamCategory_n5(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRazorpayKeyId(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRazorpayKeyId();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRazorpayKeyId();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAttempts(): Promise<Array<TestAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAttempts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAttempts();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isRazorpayConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRazorpayConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRazorpayConfigured();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setRazorpayKeyId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRazorpayKeyId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRazorpayKeyId(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitTestAttempt(arg0: bigint, arg1: Array<bigint>, arg2: bigint): Promise<TestSubmissionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestAttempt(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestAttempt(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ExamCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamCategory): ExamCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_MockTest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MockTest): MockTest {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_PracticeQuestion_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PracticeQuestion): PracticeQuestion {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_StudyNote_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyNote): StudyNote {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExamCategory]): ExamCategory | null {
    return value.length === 0 ? null : from_candid_ExamCategory_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    examCategory: [] | [_ExamCategory];
}): {
    name: string;
    examCategory?: ExamCategory;
} {
    return {
        name: value.name,
        examCategory: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.examCategory))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    test: _MockTest;
    questions: Array<_Question>;
}): {
    test: MockTest;
    questions: Array<Question>;
} {
    return {
        test: from_candid_MockTest_n20(_uploadFile, _downloadFile, value.test),
        questions: from_candid_vec_n22(_uploadFile, _downloadFile, value.questions)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    examCategory: _ExamCategory;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
}): {
    id: bigint;
    title: string;
    examCategory: ExamCategory;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
} {
    return {
        id: value.id,
        title: value.title,
        examCategory: from_candid_ExamCategory_n15(_uploadFile, _downloadFile, value.examCategory),
        durationMinutes: value.durationMinutes,
        questionIds: value.questionIds
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: string;
    question: string;
    subject: _Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: _ExamCategory;
    options: Array<string>;
}): {
    id: bigint;
    topic: string;
    question: string;
    subject: Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: ExamCategory;
    options: Array<string>;
} {
    return {
        id: value.id,
        topic: value.topic,
        question: value.question,
        subject: from_candid_Subject_n25(_uploadFile, _downloadFile, value.subject),
        explanation: value.explanation,
        correctAnswer: value.correctAnswer,
        examCategory: from_candid_ExamCategory_n15(_uploadFile, _downloadFile, value.examCategory),
        options: value.options
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: string;
    content: string;
    subject: _Subject;
    examCategory: _ExamCategory;
}): {
    id: bigint;
    topic: string;
    content: string;
    subject: Subject;
    examCategory: ExamCategory;
} {
    return {
        id: value.id,
        topic: value.topic,
        content: value.content,
        subject: from_candid_Subject_n25(_uploadFile, _downloadFile, value.subject),
        examCategory: from_candid_ExamCategory_n15(_uploadFile, _downloadFile, value.examCategory)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rms: null;
} | {
    sainikSchool: null;
} | {
    rimc: null;
} | {
    navodaya: null;
}): ExamCategory {
    return "rms" in value ? ExamCategory.rms : "sainikSchool" in value ? ExamCategory.sainikSchool : "rimc" in value ? ExamCategory.rimc : "navodaya" in value ? ExamCategory.navodaya : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gk: null;
} | {
    math: null;
} | {
    reasoning: null;
} | {
    english: null;
}): Subject {
    return "gk" in value ? Subject.gk : "math" in value ? Subject.math : "reasoning" in value ? Subject.reasoning : "english" in value ? Subject.english : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n36(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MockTest>): Array<MockTest> {
    return value.map((x)=>from_candid_MockTest_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyNote>): Array<StudyNote> {
    return value.map((x)=>from_candid_StudyNote_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PracticeQuestion>): Array<PracticeQuestion> {
    return value.map((x)=>from_candid_PracticeQuestion_n32(_uploadFile, _downloadFile, x));
}
function to_candid_ExamCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamCategory): _ExamCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionInput): _QuestionInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_StudyNoteInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyNoteInput): _StudyNoteInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: string;
    question: string;
    subject: Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: ExamCategory;
    options: Array<string>;
}): {
    topic: string;
    question: string;
    subject: _Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: _ExamCategory;
    options: Array<string>;
} {
    return {
        topic: value.topic,
        question: value.question,
        subject: to_candid_Subject_n3(_uploadFile, _downloadFile, value.subject),
        explanation: value.explanation,
        correctAnswer: value.correctAnswer,
        examCategory: to_candid_ExamCategory_n5(_uploadFile, _downloadFile, value.examCategory),
        options: value.options
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    examCategory?: ExamCategory;
}): {
    name: string;
    examCategory: [] | [_ExamCategory];
} {
    return {
        name: value.name,
        examCategory: value.examCategory ? candid_some(to_candid_ExamCategory_n5(_uploadFile, _downloadFile, value.examCategory)) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: string;
    content: string;
    subject: Subject;
    examCategory: ExamCategory;
}): {
    topic: string;
    content: string;
    subject: _Subject;
    examCategory: _ExamCategory;
} {
    return {
        topic: value.topic,
        content: value.content,
        subject: to_candid_Subject_n3(_uploadFile, _downloadFile, value.subject),
        examCategory: to_candid_ExamCategory_n5(_uploadFile, _downloadFile, value.examCategory)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    gk: null;
} | {
    math: null;
} | {
    reasoning: null;
} | {
    english: null;
} {
    return value == Subject.gk ? {
        gk: null
    } : value == Subject.math ? {
        math: null
    } : value == Subject.reasoning ? {
        reasoning: null
    } : value == Subject.english ? {
        english: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamCategory): {
    rms: null;
} | {
    sainikSchool: null;
} | {
    rimc: null;
} | {
    navodaya: null;
} {
    return value == ExamCategory.rms ? {
        rms: null
    } : value == ExamCategory.sainikSchool ? {
        sainikSchool: null
    } : value == ExamCategory.rimc ? {
        rimc: null
    } : value == ExamCategory.navodaya ? {
        navodaya: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
