/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TestAttempt {
    principal: Principal;
    total: bigint;
    answers: Array<bigint>;
    score: bigint;
    timestamp: bigint;
    timeTaken: bigint;
    testId: bigint;
}
export interface LeaderboardEntry {
    principal: Principal;
    total: bigint;
    scorePercentage: bigint;
    timestamp: bigint;
    testTitle: string;
}
export interface Question {
    id: bigint;
    topic: string;
    question: string;
    subject: Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: ExamCategory;
    options: Array<string>;
}
export interface StudyNote {
    id: bigint;
    topic: string;
    content: string;
    subject: Subject;
    examCategory: ExamCategory;
}
export interface UserProfile {
    name: string;
    examCategory?: ExamCategory;
}
export interface MockTest {
    id: bigint;
    title: string;
    examCategory: ExamCategory;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
}
export enum ExamCategory {
    rms = "rms",
    sainikSchool = "sainikSchool",
    rimc = "rimc",
    navodaya = "navodaya"
}
export enum Subject {
    gk = "gk",
    math = "math",
    reasoning = "reasoning",
    english = "english"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addQuestion(examCategory: ExamCategory, subject: Subject, topic: string, question: string, options: Array<string>, correctAnswer: bigint, explanation: string): Promise<void>;
    addStudyNote(examCategory: ExamCategory, subject: Subject, topic: string, content: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMockTest(title: string, examCategory: ExamCategory, questionIds: Array<bigint>, durationMinutes: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboardByCategory(cat: ExamCategory): Promise<Array<LeaderboardEntry>>;
    getMockTestById(id: bigint): Promise<{
        test: MockTest;
        questions: Array<Question>;
    }>;
    getMockTestsByCategory(cat: ExamCategory): Promise<Array<MockTest>>;
    getNotesByCategoryAndSubject(cat: ExamCategory, subj: Subject): Promise<Array<StudyNote>>;
    getPracticeQuestions(cat: ExamCategory, subj: Subject): Promise<Array<Question>>;
    getQuestionsByCategoryAndSubject(cat: ExamCategory, subj: Subject): Promise<Array<Question>>;
    getUserAttempts(): Promise<Array<TestAttempt>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitTestAttempt(testId: bigint, answers: Array<bigint>, timeTaken: bigint): Promise<{
        total: bigint;
        score: bigint;
    }>;
}
import type { ExamCategory as _ExamCategory, MockTest as _MockTest, Question as _Question, StudyNote as _StudyNote, Subject as _Subject, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addQuestion(arg0: ExamCategory, arg1: Subject, arg2: string, arg3: string, arg4: Array<string>, arg5: bigint, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addStudyNote(arg0: ExamCategory, arg1: Subject, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudyNote(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudyNote(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMockTest(arg0: string, arg1: ExamCategory, arg2: Array<bigint>, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMockTest(arg0, to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMockTest(arg0, to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboardByCategory(arg0: ExamCategory): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboardByCategory(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboardByCategory(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMockTestById(arg0: bigint): Promise<{
        test: MockTest;
        questions: Array<Question>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTestById(arg0);
                return from_candid_record_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTestById(arg0);
            return from_candid_record_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockTestsByCategory(arg0: ExamCategory): Promise<Array<MockTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTestsByCategory(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTestsByCategory(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByCategoryAndSubject(arg0: ExamCategory, arg1: Subject): Promise<Array<StudyNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByCategoryAndSubject(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByCategoryAndSubject(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPracticeQuestions(arg0: ExamCategory, arg1: Subject): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPracticeQuestions(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPracticeQuestions(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByCategoryAndSubject(arg0: ExamCategory, arg1: Subject): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByCategoryAndSubject(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByCategoryAndSubject(to_candid_ExamCategory_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAttempts(): Promise<Array<TestAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAttempts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAttempts();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitTestAttempt(arg0: bigint, arg1: Array<bigint>, arg2: bigint): Promise<{
        total: bigint;
        score: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestAttempt(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestAttempt(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ExamCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamCategory): ExamCategory {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_MockTest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MockTest): MockTest {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StudyNote_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyNote): StudyNote {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExamCategory]): ExamCategory | null {
    return value.length === 0 ? null : from_candid_ExamCategory_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    test: _MockTest;
    questions: Array<_Question>;
}): {
    test: MockTest;
    questions: Array<Question>;
} {
    return {
        test: from_candid_MockTest_n16(_uploadFile, _downloadFile, value.test),
        questions: from_candid_vec_n18(_uploadFile, _downloadFile, value.questions)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    examCategory: _ExamCategory;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
}): {
    id: bigint;
    title: string;
    examCategory: ExamCategory;
    durationMinutes: bigint;
    questionIds: Array<bigint>;
} {
    return {
        id: value.id,
        title: value.title,
        examCategory: from_candid_ExamCategory_n11(_uploadFile, _downloadFile, value.examCategory),
        durationMinutes: value.durationMinutes,
        questionIds: value.questionIds
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: string;
    question: string;
    subject: _Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: _ExamCategory;
    options: Array<string>;
}): {
    id: bigint;
    topic: string;
    question: string;
    subject: Subject;
    explanation: string;
    correctAnswer: bigint;
    examCategory: ExamCategory;
    options: Array<string>;
} {
    return {
        id: value.id,
        topic: value.topic,
        question: value.question,
        subject: from_candid_Subject_n21(_uploadFile, _downloadFile, value.subject),
        explanation: value.explanation,
        correctAnswer: value.correctAnswer,
        examCategory: from_candid_ExamCategory_n11(_uploadFile, _downloadFile, value.examCategory),
        options: value.options
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    topic: string;
    content: string;
    subject: _Subject;
    examCategory: _ExamCategory;
}): {
    id: bigint;
    topic: string;
    content: string;
    subject: Subject;
    examCategory: ExamCategory;
} {
    return {
        id: value.id,
        topic: value.topic,
        content: value.content,
        subject: from_candid_Subject_n21(_uploadFile, _downloadFile, value.subject),
        examCategory: from_candid_ExamCategory_n11(_uploadFile, _downloadFile, value.examCategory)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    examCategory: [] | [_ExamCategory];
}): {
    name: string;
    examCategory?: ExamCategory;
} {
    return {
        name: value.name,
        examCategory: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.examCategory))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rms: null;
} | {
    sainikSchool: null;
} | {
    rimc: null;
} | {
    navodaya: null;
}): ExamCategory {
    return "rms" in value ? ExamCategory.rms : "sainikSchool" in value ? ExamCategory.sainikSchool : "rimc" in value ? ExamCategory.rimc : "navodaya" in value ? ExamCategory.navodaya : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gk: null;
} | {
    math: null;
} | {
    reasoning: null;
} | {
    english: null;
}): Subject {
    return "gk" in value ? Subject.gk : "math" in value ? Subject.math : "reasoning" in value ? Subject.reasoning : "english" in value ? Subject.english : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MockTest>): Array<MockTest> {
    return value.map((x)=>from_candid_MockTest_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyNote>): Array<StudyNote> {
    return value.map((x)=>from_candid_StudyNote_n25(_uploadFile, _downloadFile, x));
}
function to_candid_ExamCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamCategory): _ExamCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    examCategory?: ExamCategory;
}): {
    name: string;
    examCategory: [] | [_ExamCategory];
} {
    return {
        name: value.name,
        examCategory: value.examCategory ? candid_some(to_candid_ExamCategory_n1(_uploadFile, _downloadFile, value.examCategory)) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExamCategory): {
    rms: null;
} | {
    sainikSchool: null;
} | {
    rimc: null;
} | {
    navodaya: null;
} {
    return value == ExamCategory.rms ? {
        rms: null
    } : value == ExamCategory.sainikSchool ? {
        sainikSchool: null
    } : value == ExamCategory.rimc ? {
        rimc: null
    } : value == ExamCategory.navodaya ? {
        navodaya: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    gk: null;
} | {
    math: null;
} | {
    reasoning: null;
} | {
    english: null;
} {
    return value == Subject.gk ? {
        gk: null
    } : value == Subject.math ? {
        math: null
    } : value == Subject.reasoning ? {
        reasoning: null
    } : value == Subject.english ? {
        english: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
